//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RkkInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class RkkInfo_Main
    {
        public int RkkInfo_Main_id { get; set; }
        public Nullable<int> RkkInfo_Users_id { get; set; }
        public Nullable<int> RkkInfo_Users_Post_id { get; set; }
        public Nullable<int> RkkInfo_Employees_id { get; set; }
        public Nullable<int> RkkInfo_Branch_id { get; set; }
        public Nullable<int> RkkInfo_Files_id { get; set; }
        public Nullable<int> RkkInfo_Jobs_Opening_id { get; set; }
        public Nullable<int> RkkInfo_Jobs_Vacancy_id { get; set; }
        public Nullable<int> RkkInfo_Vacation_id { get; set; }
        public Nullable<int> RkkInfo_Dismissal_id { get; set; }
    
        public virtual RkkInfo_Branch RkkInfo_Branch { get; set; }
        public virtual RkkInfo_Dismissal RkkInfo_Dismissal { get; set; }
        public virtual RkkInfo_Employees RkkInfo_Employees { get; set; }
        public virtual RkkInfo_Files RkkInfo_Files { get; set; }
        public virtual RkkInfo_Jobs_Opening RkkInfo_Jobs_Opening { get; set; }
        public virtual RkkInfo_Jobs_Vacancy RkkInfo_Jobs_Vacancy { get; set; }
        public virtual RkkInfo_Users RkkInfo_Users { get; set; }
        public virtual RkkInfo_Users_Post RkkInfo_Users_Post { get; set; }
        public virtual RkkInfo_Vacation RkkInfo_Vacation { get; set; }
    }
}
