//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RkkInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class RkkInfo_Users_Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RkkInfo_Users_Post()
        {
            this.RkkInfo_Main = new HashSet<RkkInfo_Main>();
        }
    
        public int RkkInfo_Users_Post_id { get; set; }
        public string RkkInfo_Users_Post_Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RkkInfo_Main> RkkInfo_Main { get; set; }
    }
}
