//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RkkInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class RkkInfo_Dismissal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RkkInfo_Dismissal()
        {
            this.RkkInfo_Main = new HashSet<RkkInfo_Main>();
        }
    
        public int RkkInfo_Dismissal_id { get; set; }
        public string RkkInfo_Dismissal_Name { get; set; }
        public string RkkInfo_Dismissal_First_Name { get; set; }
        public string RkkInfo_Dismissal_Last_Name { get; set; }
        public string RkkInfo_Dismissal_Position { get; set; }
        public string RkkInfo_Dismissal_Date { get; set; }
        public byte[] RkkInfo_Dismissal_Files { get; set; }
        public string RkkInfo_Dismissal_Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RkkInfo_Main> RkkInfo_Main { get; set; }
    }
}
