//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RkkInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class RkkInfo_Users
    {
        public int RkkInfo_Users_id { get; set; }
        public string RkkInfo_Users_Login { get; set; }
        public string RkkInfo_Users_Password { get; set; }
    }
}
