//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RkkInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class RkkInfo_Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RkkInfo_Employees()
        {
            this.RkkInfo_Main = new HashSet<RkkInfo_Main>();
        }
    
        public int RkkInfo_Employees_id { get; set; }
        public string RkkInfo_Employees_First_Name { get; set; }
        public string RkkInfo_Employees_Last_Name { get; set; }
        public string RkkInfo_Employees_Position { get; set; }
        public string RkkInfo_Employees_Department { get; set; }
        public string RkkInfo_Employees_Start_Date { get; set; }
        public string RkkInfo_Employees_Is_Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RkkInfo_Main> RkkInfo_Main { get; set; }
    }
}
